;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-move-beginning-of-line
        keyboard-quit
        lou/crux-smart-kill-line
        org-self-insert-command
        org-yank
        sp-backward-kill-symbol
        sp-end-of-sexp
        sp-forward-barf-sexp
        sp-forward-slurp-sexp
        sp-forward-symbol
        ))

(setq mc/cmds-to-run-once
      '(
        ))
